{# ---
version: 4.4.1
name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
url: https://jekyllrb.com
repository: https://github.com/jekyll/jekyll
site_branch: master
timezone: America/Los_Angeles
twitter:
  username: jekyllrb
logo: "/site/static/headshot.jpg" #}

# Core Info
title:                  "Andrew Hughes"
baseURL:                "https://andrewhughes.io"

docsDir:                "site"

subtitle:               "A Personal Blog"
description:            "My personal blog for all things Finance, Tech, AI, & more!"
authors:                "Andrew Hughes"

current_version:        "0.0.1"
current_ruby_version:   "5.3.7"
docs_version:           "5.3"
rfs_version:            "v10.0.0"
github_org:             "https://github.com/arh5451"
repo:                   "https://github.com/arh5451/blog-github-pages"
site_branch:            master
timezone:               Eurpoe/Zurich
x:                      "Words_with_Wood"
logo:                   "/site/static/headshot.jpg"
themes:                 "https://themes.getbootstrap.com/"
icons:                  "https://icons.getbootstrap.com/"

## google_analytics_id: UA-50755011-1
## google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
## cloudinary_url: https://res.cloudinary.com/jekyll/image/upload/f_auto,q_auto,w_404 intersting it is so they can use CLI interface with rails or something? maybye look into more later

# Where things are
source              : .
destination         : ./_site
collections_dir     : .
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/news/:year/:month/:day/:title/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _posts
    type: posts
  values:
    layout: news_item
- scope:
    path: _tutorials
    type: tutorials
  values:
    layout: tutorials
- scope:
    path: ''
  values:
    image: "/img/jekyll-og.png"

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : null
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : date
paginate_path       : /page:num
timezone            : null

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

# Markdown Processors
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
